language: c

dist: trusty
sudo: false

addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - ninja-build
    - python3.5
    - python3-pip

_packages:
  - &gcc49-packages
    apt:
      sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
      packages:
      - gcc-4.9
      - g++-4.9
      - ninja-build
      - python3.5
      - python3-pip

_stylecheck: &stylecheck

stages:
  - stylecheck
  - build

jobs:
  include:
  - stage: stylecheck
    install: skip
    script:
    - true
    after_success:
    - echo "Style check passed."

  # Linux GCC 4.9
  - stage: build
    os: linux
    compiler: gcc-4.9
    addons: *gcc49-packages

  # Linux Debug, GCC 4.6
  - stage: build
    os: linux
    compiler: gcc

  # Linux RelWithDebInfo, GCC 4.6
  - stage: build
    os: linux
    compiler: gcc

  # OSX GCC 4.9
  - stage: build
    os: osx
    osx_image: xcode8
    compiler: gcc-4.9

  # OSX Clang
  - stage: build
    os: osx
    compiler: clang

  allow_failures:
  - stage: build
    compiler: gcc

before_install:
  - |
      mkdir -p ~/.local/bin
      test -x /usr/bin/python3.5 && ln -sf $_ ~/.local/bin/python3
      export PATH="~/.local/bin:$PATH"
      export PATH="$(python2 -m site --user-base)/bin:$PATH"
      export PATH="$(python3 -m site --user-base)/bin:$PATH"
  - |
      export CXX=${CC/gcc/g++}
      export CXX=${CXX/clang/clang++}
      $CC --version
      $CXX --version
      python3 --version

install:
  - travis_retry python3 -m pip install --user meson==0.48
  - travis_retry python2 -m pip install --user cram==0.7

script:
  - meson build .
  - cd build
  - ninja
  - ninja test

#after_success:
#  - |
#      if [ "$COVERAGE" = "ON" ]; then
#        make gcov
#        bash <(curl -s https://codecov.io/bash)
#      fi
#
#before_deploy:
#  - make install
#  - tar -cvjf ../criterion-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x86_64.tar.bz2 criterion-${TRAVIS_TAG}
#  - cd ..
#  - |
#      if [ "$TRAVIS_OS_NAME" = "osx" ]; then
#        brew install gnu-tar --with-default-names
#        export PATH="/usr/local/bin:$PATH"
#      fi
#  - ./.cmake/git-archive-all.sh --prefix criterion-${TRAVIS_TAG} criterion-${TRAVIS_TAG}.tar && bzip2 $_
#
#addons:
#  coverity_scan:
#    project:
#      name: "Snaipe/Criterion"
#      description: "A KISS, Cross-platform C unit testing framework"
#    notification_email: franklinmathieu@gmail.com
#    build_command_prepend: "cmake ."
#    build_command: "make -j4"
#    branch_pattern: coverity_scan

#deploy:
#  provider: releases
#  edge:
#    branch: releases-fix
#  skip_cleanup: true
#  file:
#    - criterion-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x86_64.tar.bz2
#    - criterion-${TRAVIS_TAG}.tar.bz2
#  on:
#    repo: Snaipe/Criterion
#    tags: true
#    condition: $DEPLOY = true
#  api_key:
#    secure: >-
#      d3l2Ohb2FF3tSXku1d0ASR5dntdnQ48Jyc39IEloDBx
#      FXCselCkYruUQv6p0TA3P+Dmrz4wS7/AFlBMMsQ3XfG
#      FVIOnITiTaGWg5fEpIf7zYsDf0zECPE0MOHMGqJMn3/
#      SrSKdtEA4N84Q4JS7Ou+ewG65mxUDO5Ce60OoEG5JA=
